// Code generated by counterfeiter. DO NOT EDIT.
package lbfakes

import (
	"context"
	"srsx/internal/lb"
	"sync"
)

type FakeHLSService struct {
	LoadHLSBySPBHIDStub        func(context.Context, string) (lb.HLSPlayStream, error)
	loadHLSBySPBHIDMutex       sync.RWMutex
	loadHLSBySPBHIDArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	loadHLSBySPBHIDReturns struct {
		result1 lb.HLSPlayStream
		result2 error
	}
	loadHLSBySPBHIDReturnsOnCall map[int]struct {
		result1 lb.HLSPlayStream
		result2 error
	}
	LoadOrStoreHLSStub        func(context.Context, string, lb.HLSPlayStream) (lb.HLSPlayStream, error)
	loadOrStoreHLSMutex       sync.RWMutex
	loadOrStoreHLSArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 lb.HLSPlayStream
	}
	loadOrStoreHLSReturns struct {
		result1 lb.HLSPlayStream
		result2 error
	}
	loadOrStoreHLSReturnsOnCall map[int]struct {
		result1 lb.HLSPlayStream
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHLSService) LoadHLSBySPBHID(arg1 context.Context, arg2 string) (lb.HLSPlayStream, error) {
	fake.loadHLSBySPBHIDMutex.Lock()
	ret, specificReturn := fake.loadHLSBySPBHIDReturnsOnCall[len(fake.loadHLSBySPBHIDArgsForCall)]
	fake.loadHLSBySPBHIDArgsForCall = append(fake.loadHLSBySPBHIDArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.LoadHLSBySPBHIDStub
	fakeReturns := fake.loadHLSBySPBHIDReturns
	fake.recordInvocation("LoadHLSBySPBHID", []interface{}{arg1, arg2})
	fake.loadHLSBySPBHIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeHLSService) LoadHLSBySPBHIDCallCount() int {
	fake.loadHLSBySPBHIDMutex.RLock()
	defer fake.loadHLSBySPBHIDMutex.RUnlock()
	return len(fake.loadHLSBySPBHIDArgsForCall)
}

func (fake *FakeHLSService) LoadHLSBySPBHIDCalls(stub func(context.Context, string) (lb.HLSPlayStream, error)) {
	fake.loadHLSBySPBHIDMutex.Lock()
	defer fake.loadHLSBySPBHIDMutex.Unlock()
	fake.LoadHLSBySPBHIDStub = stub
}

func (fake *FakeHLSService) LoadHLSBySPBHIDArgsForCall(i int) (context.Context, string) {
	fake.loadHLSBySPBHIDMutex.RLock()
	defer fake.loadHLSBySPBHIDMutex.RUnlock()
	argsForCall := fake.loadHLSBySPBHIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeHLSService) LoadHLSBySPBHIDReturns(result1 lb.HLSPlayStream, result2 error) {
	fake.loadHLSBySPBHIDMutex.Lock()
	defer fake.loadHLSBySPBHIDMutex.Unlock()
	fake.LoadHLSBySPBHIDStub = nil
	fake.loadHLSBySPBHIDReturns = struct {
		result1 lb.HLSPlayStream
		result2 error
	}{result1, result2}
}

func (fake *FakeHLSService) LoadHLSBySPBHIDReturnsOnCall(i int, result1 lb.HLSPlayStream, result2 error) {
	fake.loadHLSBySPBHIDMutex.Lock()
	defer fake.loadHLSBySPBHIDMutex.Unlock()
	fake.LoadHLSBySPBHIDStub = nil
	if fake.loadHLSBySPBHIDReturnsOnCall == nil {
		fake.loadHLSBySPBHIDReturnsOnCall = make(map[int]struct {
			result1 lb.HLSPlayStream
			result2 error
		})
	}
	fake.loadHLSBySPBHIDReturnsOnCall[i] = struct {
		result1 lb.HLSPlayStream
		result2 error
	}{result1, result2}
}

func (fake *FakeHLSService) LoadOrStoreHLS(arg1 context.Context, arg2 string, arg3 lb.HLSPlayStream) (lb.HLSPlayStream, error) {
	fake.loadOrStoreHLSMutex.Lock()
	ret, specificReturn := fake.loadOrStoreHLSReturnsOnCall[len(fake.loadOrStoreHLSArgsForCall)]
	fake.loadOrStoreHLSArgsForCall = append(fake.loadOrStoreHLSArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 lb.HLSPlayStream
	}{arg1, arg2, arg3})
	stub := fake.LoadOrStoreHLSStub
	fakeReturns := fake.loadOrStoreHLSReturns
	fake.recordInvocation("LoadOrStoreHLS", []interface{}{arg1, arg2, arg3})
	fake.loadOrStoreHLSMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeHLSService) LoadOrStoreHLSCallCount() int {
	fake.loadOrStoreHLSMutex.RLock()
	defer fake.loadOrStoreHLSMutex.RUnlock()
	return len(fake.loadOrStoreHLSArgsForCall)
}

func (fake *FakeHLSService) LoadOrStoreHLSCalls(stub func(context.Context, string, lb.HLSPlayStream) (lb.HLSPlayStream, error)) {
	fake.loadOrStoreHLSMutex.Lock()
	defer fake.loadOrStoreHLSMutex.Unlock()
	fake.LoadOrStoreHLSStub = stub
}

func (fake *FakeHLSService) LoadOrStoreHLSArgsForCall(i int) (context.Context, string, lb.HLSPlayStream) {
	fake.loadOrStoreHLSMutex.RLock()
	defer fake.loadOrStoreHLSMutex.RUnlock()
	argsForCall := fake.loadOrStoreHLSArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeHLSService) LoadOrStoreHLSReturns(result1 lb.HLSPlayStream, result2 error) {
	fake.loadOrStoreHLSMutex.Lock()
	defer fake.loadOrStoreHLSMutex.Unlock()
	fake.LoadOrStoreHLSStub = nil
	fake.loadOrStoreHLSReturns = struct {
		result1 lb.HLSPlayStream
		result2 error
	}{result1, result2}
}

func (fake *FakeHLSService) LoadOrStoreHLSReturnsOnCall(i int, result1 lb.HLSPlayStream, result2 error) {
	fake.loadOrStoreHLSMutex.Lock()
	defer fake.loadOrStoreHLSMutex.Unlock()
	fake.LoadOrStoreHLSStub = nil
	if fake.loadOrStoreHLSReturnsOnCall == nil {
		fake.loadOrStoreHLSReturnsOnCall = make(map[int]struct {
			result1 lb.HLSPlayStream
			result2 error
		})
	}
	fake.loadOrStoreHLSReturnsOnCall[i] = struct {
		result1 lb.HLSPlayStream
		result2 error
	}{result1, result2}
}

func (fake *FakeHLSService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHLSService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ lb.HLSService = new(FakeHLSService)
