// Code generated by counterfeiter. DO NOT EDIT.
package lbfakes

import (
	"context"
	"srsx/internal/lb"
	"sync"
)

type FakeOriginLoadBalancer struct {
	InitializeStub        func(context.Context) error
	initializeMutex       sync.RWMutex
	initializeArgsForCall []struct {
		arg1 context.Context
	}
	initializeReturns struct {
		result1 error
	}
	initializeReturnsOnCall map[int]struct {
		result1 error
	}
	LoadHLSBySPBHIDStub        func(context.Context, string) (lb.HLSPlayStream, error)
	loadHLSBySPBHIDMutex       sync.RWMutex
	loadHLSBySPBHIDArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	loadHLSBySPBHIDReturns struct {
		result1 lb.HLSPlayStream
		result2 error
	}
	loadHLSBySPBHIDReturnsOnCall map[int]struct {
		result1 lb.HLSPlayStream
		result2 error
	}
	LoadOrStoreHLSStub        func(context.Context, string, lb.HLSPlayStream) (lb.HLSPlayStream, error)
	loadOrStoreHLSMutex       sync.RWMutex
	loadOrStoreHLSArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 lb.HLSPlayStream
	}
	loadOrStoreHLSReturns struct {
		result1 lb.HLSPlayStream
		result2 error
	}
	loadOrStoreHLSReturnsOnCall map[int]struct {
		result1 lb.HLSPlayStream
		result2 error
	}
	LoadWebRTCByUfragStub        func(context.Context, string) (lb.RTCConnection, error)
	loadWebRTCByUfragMutex       sync.RWMutex
	loadWebRTCByUfragArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	loadWebRTCByUfragReturns struct {
		result1 lb.RTCConnection
		result2 error
	}
	loadWebRTCByUfragReturnsOnCall map[int]struct {
		result1 lb.RTCConnection
		result2 error
	}
	PickStub        func(context.Context, string) (*lb.OriginServer, error)
	pickMutex       sync.RWMutex
	pickArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	pickReturns struct {
		result1 *lb.OriginServer
		result2 error
	}
	pickReturnsOnCall map[int]struct {
		result1 *lb.OriginServer
		result2 error
	}
	StoreWebRTCStub        func(context.Context, string, lb.RTCConnection) error
	storeWebRTCMutex       sync.RWMutex
	storeWebRTCArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 lb.RTCConnection
	}
	storeWebRTCReturns struct {
		result1 error
	}
	storeWebRTCReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateStub        func(context.Context, *lb.OriginServer) error
	updateMutex       sync.RWMutex
	updateArgsForCall []struct {
		arg1 context.Context
		arg2 *lb.OriginServer
	}
	updateReturns struct {
		result1 error
	}
	updateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeOriginLoadBalancer) Initialize(arg1 context.Context) error {
	fake.initializeMutex.Lock()
	ret, specificReturn := fake.initializeReturnsOnCall[len(fake.initializeArgsForCall)]
	fake.initializeArgsForCall = append(fake.initializeArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.InitializeStub
	fakeReturns := fake.initializeReturns
	fake.recordInvocation("Initialize", []interface{}{arg1})
	fake.initializeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeOriginLoadBalancer) InitializeCallCount() int {
	fake.initializeMutex.RLock()
	defer fake.initializeMutex.RUnlock()
	return len(fake.initializeArgsForCall)
}

func (fake *FakeOriginLoadBalancer) InitializeCalls(stub func(context.Context) error) {
	fake.initializeMutex.Lock()
	defer fake.initializeMutex.Unlock()
	fake.InitializeStub = stub
}

func (fake *FakeOriginLoadBalancer) InitializeArgsForCall(i int) context.Context {
	fake.initializeMutex.RLock()
	defer fake.initializeMutex.RUnlock()
	argsForCall := fake.initializeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeOriginLoadBalancer) InitializeReturns(result1 error) {
	fake.initializeMutex.Lock()
	defer fake.initializeMutex.Unlock()
	fake.InitializeStub = nil
	fake.initializeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeOriginLoadBalancer) InitializeReturnsOnCall(i int, result1 error) {
	fake.initializeMutex.Lock()
	defer fake.initializeMutex.Unlock()
	fake.InitializeStub = nil
	if fake.initializeReturnsOnCall == nil {
		fake.initializeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.initializeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeOriginLoadBalancer) LoadHLSBySPBHID(arg1 context.Context, arg2 string) (lb.HLSPlayStream, error) {
	fake.loadHLSBySPBHIDMutex.Lock()
	ret, specificReturn := fake.loadHLSBySPBHIDReturnsOnCall[len(fake.loadHLSBySPBHIDArgsForCall)]
	fake.loadHLSBySPBHIDArgsForCall = append(fake.loadHLSBySPBHIDArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.LoadHLSBySPBHIDStub
	fakeReturns := fake.loadHLSBySPBHIDReturns
	fake.recordInvocation("LoadHLSBySPBHID", []interface{}{arg1, arg2})
	fake.loadHLSBySPBHIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeOriginLoadBalancer) LoadHLSBySPBHIDCallCount() int {
	fake.loadHLSBySPBHIDMutex.RLock()
	defer fake.loadHLSBySPBHIDMutex.RUnlock()
	return len(fake.loadHLSBySPBHIDArgsForCall)
}

func (fake *FakeOriginLoadBalancer) LoadHLSBySPBHIDCalls(stub func(context.Context, string) (lb.HLSPlayStream, error)) {
	fake.loadHLSBySPBHIDMutex.Lock()
	defer fake.loadHLSBySPBHIDMutex.Unlock()
	fake.LoadHLSBySPBHIDStub = stub
}

func (fake *FakeOriginLoadBalancer) LoadHLSBySPBHIDArgsForCall(i int) (context.Context, string) {
	fake.loadHLSBySPBHIDMutex.RLock()
	defer fake.loadHLSBySPBHIDMutex.RUnlock()
	argsForCall := fake.loadHLSBySPBHIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeOriginLoadBalancer) LoadHLSBySPBHIDReturns(result1 lb.HLSPlayStream, result2 error) {
	fake.loadHLSBySPBHIDMutex.Lock()
	defer fake.loadHLSBySPBHIDMutex.Unlock()
	fake.LoadHLSBySPBHIDStub = nil
	fake.loadHLSBySPBHIDReturns = struct {
		result1 lb.HLSPlayStream
		result2 error
	}{result1, result2}
}

func (fake *FakeOriginLoadBalancer) LoadHLSBySPBHIDReturnsOnCall(i int, result1 lb.HLSPlayStream, result2 error) {
	fake.loadHLSBySPBHIDMutex.Lock()
	defer fake.loadHLSBySPBHIDMutex.Unlock()
	fake.LoadHLSBySPBHIDStub = nil
	if fake.loadHLSBySPBHIDReturnsOnCall == nil {
		fake.loadHLSBySPBHIDReturnsOnCall = make(map[int]struct {
			result1 lb.HLSPlayStream
			result2 error
		})
	}
	fake.loadHLSBySPBHIDReturnsOnCall[i] = struct {
		result1 lb.HLSPlayStream
		result2 error
	}{result1, result2}
}

func (fake *FakeOriginLoadBalancer) LoadOrStoreHLS(arg1 context.Context, arg2 string, arg3 lb.HLSPlayStream) (lb.HLSPlayStream, error) {
	fake.loadOrStoreHLSMutex.Lock()
	ret, specificReturn := fake.loadOrStoreHLSReturnsOnCall[len(fake.loadOrStoreHLSArgsForCall)]
	fake.loadOrStoreHLSArgsForCall = append(fake.loadOrStoreHLSArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 lb.HLSPlayStream
	}{arg1, arg2, arg3})
	stub := fake.LoadOrStoreHLSStub
	fakeReturns := fake.loadOrStoreHLSReturns
	fake.recordInvocation("LoadOrStoreHLS", []interface{}{arg1, arg2, arg3})
	fake.loadOrStoreHLSMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeOriginLoadBalancer) LoadOrStoreHLSCallCount() int {
	fake.loadOrStoreHLSMutex.RLock()
	defer fake.loadOrStoreHLSMutex.RUnlock()
	return len(fake.loadOrStoreHLSArgsForCall)
}

func (fake *FakeOriginLoadBalancer) LoadOrStoreHLSCalls(stub func(context.Context, string, lb.HLSPlayStream) (lb.HLSPlayStream, error)) {
	fake.loadOrStoreHLSMutex.Lock()
	defer fake.loadOrStoreHLSMutex.Unlock()
	fake.LoadOrStoreHLSStub = stub
}

func (fake *FakeOriginLoadBalancer) LoadOrStoreHLSArgsForCall(i int) (context.Context, string, lb.HLSPlayStream) {
	fake.loadOrStoreHLSMutex.RLock()
	defer fake.loadOrStoreHLSMutex.RUnlock()
	argsForCall := fake.loadOrStoreHLSArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeOriginLoadBalancer) LoadOrStoreHLSReturns(result1 lb.HLSPlayStream, result2 error) {
	fake.loadOrStoreHLSMutex.Lock()
	defer fake.loadOrStoreHLSMutex.Unlock()
	fake.LoadOrStoreHLSStub = nil
	fake.loadOrStoreHLSReturns = struct {
		result1 lb.HLSPlayStream
		result2 error
	}{result1, result2}
}

func (fake *FakeOriginLoadBalancer) LoadOrStoreHLSReturnsOnCall(i int, result1 lb.HLSPlayStream, result2 error) {
	fake.loadOrStoreHLSMutex.Lock()
	defer fake.loadOrStoreHLSMutex.Unlock()
	fake.LoadOrStoreHLSStub = nil
	if fake.loadOrStoreHLSReturnsOnCall == nil {
		fake.loadOrStoreHLSReturnsOnCall = make(map[int]struct {
			result1 lb.HLSPlayStream
			result2 error
		})
	}
	fake.loadOrStoreHLSReturnsOnCall[i] = struct {
		result1 lb.HLSPlayStream
		result2 error
	}{result1, result2}
}

func (fake *FakeOriginLoadBalancer) LoadWebRTCByUfrag(arg1 context.Context, arg2 string) (lb.RTCConnection, error) {
	fake.loadWebRTCByUfragMutex.Lock()
	ret, specificReturn := fake.loadWebRTCByUfragReturnsOnCall[len(fake.loadWebRTCByUfragArgsForCall)]
	fake.loadWebRTCByUfragArgsForCall = append(fake.loadWebRTCByUfragArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.LoadWebRTCByUfragStub
	fakeReturns := fake.loadWebRTCByUfragReturns
	fake.recordInvocation("LoadWebRTCByUfrag", []interface{}{arg1, arg2})
	fake.loadWebRTCByUfragMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeOriginLoadBalancer) LoadWebRTCByUfragCallCount() int {
	fake.loadWebRTCByUfragMutex.RLock()
	defer fake.loadWebRTCByUfragMutex.RUnlock()
	return len(fake.loadWebRTCByUfragArgsForCall)
}

func (fake *FakeOriginLoadBalancer) LoadWebRTCByUfragCalls(stub func(context.Context, string) (lb.RTCConnection, error)) {
	fake.loadWebRTCByUfragMutex.Lock()
	defer fake.loadWebRTCByUfragMutex.Unlock()
	fake.LoadWebRTCByUfragStub = stub
}

func (fake *FakeOriginLoadBalancer) LoadWebRTCByUfragArgsForCall(i int) (context.Context, string) {
	fake.loadWebRTCByUfragMutex.RLock()
	defer fake.loadWebRTCByUfragMutex.RUnlock()
	argsForCall := fake.loadWebRTCByUfragArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeOriginLoadBalancer) LoadWebRTCByUfragReturns(result1 lb.RTCConnection, result2 error) {
	fake.loadWebRTCByUfragMutex.Lock()
	defer fake.loadWebRTCByUfragMutex.Unlock()
	fake.LoadWebRTCByUfragStub = nil
	fake.loadWebRTCByUfragReturns = struct {
		result1 lb.RTCConnection
		result2 error
	}{result1, result2}
}

func (fake *FakeOriginLoadBalancer) LoadWebRTCByUfragReturnsOnCall(i int, result1 lb.RTCConnection, result2 error) {
	fake.loadWebRTCByUfragMutex.Lock()
	defer fake.loadWebRTCByUfragMutex.Unlock()
	fake.LoadWebRTCByUfragStub = nil
	if fake.loadWebRTCByUfragReturnsOnCall == nil {
		fake.loadWebRTCByUfragReturnsOnCall = make(map[int]struct {
			result1 lb.RTCConnection
			result2 error
		})
	}
	fake.loadWebRTCByUfragReturnsOnCall[i] = struct {
		result1 lb.RTCConnection
		result2 error
	}{result1, result2}
}

func (fake *FakeOriginLoadBalancer) Pick(arg1 context.Context, arg2 string) (*lb.OriginServer, error) {
	fake.pickMutex.Lock()
	ret, specificReturn := fake.pickReturnsOnCall[len(fake.pickArgsForCall)]
	fake.pickArgsForCall = append(fake.pickArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.PickStub
	fakeReturns := fake.pickReturns
	fake.recordInvocation("Pick", []interface{}{arg1, arg2})
	fake.pickMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeOriginLoadBalancer) PickCallCount() int {
	fake.pickMutex.RLock()
	defer fake.pickMutex.RUnlock()
	return len(fake.pickArgsForCall)
}

func (fake *FakeOriginLoadBalancer) PickCalls(stub func(context.Context, string) (*lb.OriginServer, error)) {
	fake.pickMutex.Lock()
	defer fake.pickMutex.Unlock()
	fake.PickStub = stub
}

func (fake *FakeOriginLoadBalancer) PickArgsForCall(i int) (context.Context, string) {
	fake.pickMutex.RLock()
	defer fake.pickMutex.RUnlock()
	argsForCall := fake.pickArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeOriginLoadBalancer) PickReturns(result1 *lb.OriginServer, result2 error) {
	fake.pickMutex.Lock()
	defer fake.pickMutex.Unlock()
	fake.PickStub = nil
	fake.pickReturns = struct {
		result1 *lb.OriginServer
		result2 error
	}{result1, result2}
}

func (fake *FakeOriginLoadBalancer) PickReturnsOnCall(i int, result1 *lb.OriginServer, result2 error) {
	fake.pickMutex.Lock()
	defer fake.pickMutex.Unlock()
	fake.PickStub = nil
	if fake.pickReturnsOnCall == nil {
		fake.pickReturnsOnCall = make(map[int]struct {
			result1 *lb.OriginServer
			result2 error
		})
	}
	fake.pickReturnsOnCall[i] = struct {
		result1 *lb.OriginServer
		result2 error
	}{result1, result2}
}

func (fake *FakeOriginLoadBalancer) StoreWebRTC(arg1 context.Context, arg2 string, arg3 lb.RTCConnection) error {
	fake.storeWebRTCMutex.Lock()
	ret, specificReturn := fake.storeWebRTCReturnsOnCall[len(fake.storeWebRTCArgsForCall)]
	fake.storeWebRTCArgsForCall = append(fake.storeWebRTCArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 lb.RTCConnection
	}{arg1, arg2, arg3})
	stub := fake.StoreWebRTCStub
	fakeReturns := fake.storeWebRTCReturns
	fake.recordInvocation("StoreWebRTC", []interface{}{arg1, arg2, arg3})
	fake.storeWebRTCMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeOriginLoadBalancer) StoreWebRTCCallCount() int {
	fake.storeWebRTCMutex.RLock()
	defer fake.storeWebRTCMutex.RUnlock()
	return len(fake.storeWebRTCArgsForCall)
}

func (fake *FakeOriginLoadBalancer) StoreWebRTCCalls(stub func(context.Context, string, lb.RTCConnection) error) {
	fake.storeWebRTCMutex.Lock()
	defer fake.storeWebRTCMutex.Unlock()
	fake.StoreWebRTCStub = stub
}

func (fake *FakeOriginLoadBalancer) StoreWebRTCArgsForCall(i int) (context.Context, string, lb.RTCConnection) {
	fake.storeWebRTCMutex.RLock()
	defer fake.storeWebRTCMutex.RUnlock()
	argsForCall := fake.storeWebRTCArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeOriginLoadBalancer) StoreWebRTCReturns(result1 error) {
	fake.storeWebRTCMutex.Lock()
	defer fake.storeWebRTCMutex.Unlock()
	fake.StoreWebRTCStub = nil
	fake.storeWebRTCReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeOriginLoadBalancer) StoreWebRTCReturnsOnCall(i int, result1 error) {
	fake.storeWebRTCMutex.Lock()
	defer fake.storeWebRTCMutex.Unlock()
	fake.StoreWebRTCStub = nil
	if fake.storeWebRTCReturnsOnCall == nil {
		fake.storeWebRTCReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.storeWebRTCReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeOriginLoadBalancer) Update(arg1 context.Context, arg2 *lb.OriginServer) error {
	fake.updateMutex.Lock()
	ret, specificReturn := fake.updateReturnsOnCall[len(fake.updateArgsForCall)]
	fake.updateArgsForCall = append(fake.updateArgsForCall, struct {
		arg1 context.Context
		arg2 *lb.OriginServer
	}{arg1, arg2})
	stub := fake.UpdateStub
	fakeReturns := fake.updateReturns
	fake.recordInvocation("Update", []interface{}{arg1, arg2})
	fake.updateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeOriginLoadBalancer) UpdateCallCount() int {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return len(fake.updateArgsForCall)
}

func (fake *FakeOriginLoadBalancer) UpdateCalls(stub func(context.Context, *lb.OriginServer) error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = stub
}

func (fake *FakeOriginLoadBalancer) UpdateArgsForCall(i int) (context.Context, *lb.OriginServer) {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	argsForCall := fake.updateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeOriginLoadBalancer) UpdateReturns(result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	fake.updateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeOriginLoadBalancer) UpdateReturnsOnCall(i int, result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	if fake.updateReturnsOnCall == nil {
		fake.updateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeOriginLoadBalancer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeOriginLoadBalancer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ lb.OriginLoadBalancer = new(FakeOriginLoadBalancer)
