//
// Copyright (c) 2013-2026 The SRS Authors
//
// SPDX-License-Identifier: MIT
//

#ifndef SRS_APP_FORWARD_HPP
#define SRS_APP_FORWARD_HPP

#include <srs_core.hpp>

#include <map>
#include <string>
#include <vector>

#include <srs_app_st.hpp>

class ISrsProtocolReadWriter;
class SrsMediaPacket;
class SrsOnMetaDataPacket;
class SrsMessageQueue;
class SrsRtmpJitter;
class SrsRtmpClient;
class ISrsRequest;
class SrsLiveSource;
class SrsOriginHub;
class ISrsOriginHub;
class SrsKbps;
class SrsSimpleRtmpClient;
class ISrsBasicRtmpClient;
class ISrsAppFactory;
class ISrsAppConfig;
class SrsJsonObject;
class ISrsRand;

// The forward interface.
class ISrsForwarder
{
public:
    ISrsForwarder();
    virtual ~ISrsForwarder();

public:
    virtual srs_error_t initialize(ISrsRequest *r, std::string ep) = 0;
    virtual void set_queue_size(srs_utime_t queue_size) = 0;
    virtual srs_error_t on_publish() = 0;
    virtual void on_unpublish() = 0;
    virtual srs_error_t on_meta_data(SrsMediaPacket *shared_metadata) = 0;
    virtual srs_error_t on_audio(SrsMediaPacket *shared_audio) = 0;
    virtual srs_error_t on_video(SrsMediaPacket *shared_video) = 0;
    // Dumps the state of forwarder, such as connecting or forwarding, the last error and counters.
    virtual void dumps(SrsJsonObject *obj) = 0;
};

// Forward the stream to other servers.
class SrsForwarder : public ISrsCoroutineHandler, public ISrsForwarder
{
// clang-format off
SRS_DECLARE_PRIVATE: // clang-format on
    ISrsAppFactory *app_factory_;
    ISrsAppConfig *config_;

// clang-format off
SRS_DECLARE_PRIVATE: // clang-format on
    // The ep to forward, server[:port].
    std::string ep_forward_;
    ISrsRequest *req_;

// clang-format off
SRS_DECLARE_PRIVATE: // clang-format on
    // The source or stream context id to bind to.
    SrsContextId source_cid_;

// clang-format off
SRS_DECLARE_PRIVATE: // clang-format on
    ISrsCoroutine *trd_;

// clang-format off
SRS_DECLARE_PRIVATE: // clang-format on
    ISrsOriginHub *hub_;
    ISrsBasicRtmpClient *sdk_;
    SrsRtmpJitter *jitter_;
    SrsMessageQueue *queue_;
    // Cache the sequence header for retry when slave is failed.
    SrsMediaPacket *sh_audio_;
    SrsMediaPacket *sh_video_;

// clang-format off
SRS_DECLARE_PRIVATE: // clang-format on
    // The state of forwarder, idle, connecting, forwarding or retrying.
    std::string state_;
    // The time when the state changed.
    srs_utime_t state_at_;
    // The last error and the time it happened.
    std::string last_error_;
    srs_utime_t last_error_at_;
    // The number of connections that published successfully, and the number of failed attempts.
    int64_t connects_;
    int64_t failures_;
    // The media bytes sent to the destination, and the video frames dropped while waiting for a keyframe.
    int64_t send_bytes_;
    int64_t dropped_frames_;
    // Whether to drop the video frames until a keyframe, when connected or the queue is overflow.
    bool wait_keyframe_;

public:
    SrsForwarder(ISrsOriginHub *h);
    virtual ~SrsForwarder();

public:
    virtual srs_error_t initialize(ISrsRequest *r, std::string ep);
    virtual void set_queue_size(srs_utime_t queue_size);

public:
    virtual srs_error_t on_publish();
    virtual void on_unpublish();
    // Forward the audio packet.
    // @param shared_metadata, directly ptr, copy it if need to save it.
    virtual srs_error_t on_meta_data(SrsMediaPacket *shared_metadata);
    // Forward the audio packet.
    // @param shared_audio, directly ptr, copy it if need to save it.
    virtual srs_error_t on_audio(SrsMediaPacket *shared_audio);
    // Forward the video packet.
    // @param shared_video, directly ptr, copy it if need to save it.
    virtual srs_error_t on_video(SrsMediaPacket *shared_video);
    virtual void dumps(SrsJsonObject *obj);
    // Interface ISrsReusableThread2Handler.
public:
    virtual srs_error_t cycle();

// clang-format off
SRS_DECLARE_PRIVATE: // clang-format on
    virtual srs_error_t do_cycle();

// clang-format off
SRS_DECLARE_PRIVATE: // clang-format on
    virtual srs_error_t forward();
    virtual void set_state(std::string state);
};

// Hide the stream name and the query string of an RTMP url, because they carry the stream key, for
// example, rtmp://host:1935/live/key?token=xxx is rtmp://host:1935/live/***
extern std::string srs_forward_redact_url(std::string url);

// Hide the stream and query in the error of RTMP client, because they carry the stream key, for
// example, "publish failed, stream=key?token=xxx, stream_id=1" is "publish failed, stream=***, stream_id=1"
extern std::string srs_forward_redact_error(std::string msg);

// A forward destination of a stream, which is added or removed by the HTTP API at runtime. It's
// keyed by the stream, so it is kept when the stream is unpublished and published again.
class SrsForwardDestination
{
public:
    // The unique id of destination, specified by the caller or generated by SRS.
    std::string id_;
    // The stream to forward, the vhost is the name of the vhost section in config.
    std::string vhost_;
    std::string app_;
    std::string stream_;
    // The RTMP url to forward to, for example, rtmp://host:port/app/stream?param
    std::string url_;
    // The time when the destination is created.
    srs_utime_t created_at_;

public:
    SrsForwardDestination();
    virtual ~SrsForwardDestination();

public:
    // The stream url, the key to match the live source, see ISrsRequest::get_stream_url()
    std::string stream_url();
    SrsForwardDestination *copy();
};

// The handler of forward destinations of a stream, it's the origin hub of the live source,
// which is subscribed to the destinations when the stream is publishing.
class ISrsForwardDestinationHandler
{
public:
    ISrsForwardDestinationHandler();
    virtual ~ISrsForwardDestinationHandler();

public:
    // Start forwarding to a new destination, without touching the other destinations.
    virtual srs_error_t on_forward_destination_add(SrsForwardDestination *dest) = 0;
    // Stop forwarding to a destination, without touching the other destinations.
    // @remark This will switch the coroutine context, for it stops the forwarder coroutine.
    virtual void on_forward_destination_remove(std::string id) = 0;
    // Dumps the state of the destination.
    virtual void on_forward_destination_dumps(std::string id, SrsJsonObject *obj) = 0;
};

// The forward destinations of all streams, managed by the HTTP API.
class ISrsForwardDestinations
{
public:
    ISrsForwardDestinations();
    virtual ~ISrsForwardDestinations();

public:
    // Add a destination, which is copied by the manager. If the id already exists with the same stream and
    // url, it's ignored and the created is false. If the stream is publishing, start forwarding to it.
    // @param pstored Optional, the destination stored by the manager, with the generated id if not specified.
    virtual srs_error_t add(SrsForwardDestination *dest, bool *created, SrsForwardDestination **pstored = NULL) = 0;
    // Remove the destination by id. If the stream is publishing, stop forwarding to it.
    // @remark This will switch the coroutine context, for it stops the forwarder coroutine.
    virtual srs_error_t remove(std::string id) = 0;
    // Find the destination by id, return NULL if not found.
    virtual SrsForwardDestination *find(std::string id) = 0;
    // Fetch the destinations of the stream url, or all destinations if the stream url is empty.
    virtual void fetch(std::string stream_url, std::vector<SrsForwardDestination *> &dests) = 0;
    // Dumps the destination and its forwarding state.
    virtual void dumps(SrsForwardDestination *dest, SrsJsonObject *obj) = 0;

public:
    // Subscribe to the destinations of the stream url, when the stream starts publishing.
    virtual void subscribe(std::string stream_url, ISrsForwardDestinationHandler *handler) = 0;
    // Unsubscribe from the destinations of the stream url, when the stream stops publishing.
    virtual void unsubscribe(std::string stream_url, ISrsForwardDestinationHandler *handler) = 0;
};

// The max number of forward destinations of all streams.
#define SRS_FORWARD_DESTINATIONS_MAX 1024

// The forward destinations of all streams, managed by the HTTP API.
class SrsForwardDestinations : public ISrsForwardDestinations
{
// clang-format off
SRS_DECLARE_PRIVATE: // clang-format on
    // All destinations, in the order of creation.
    std::vector<SrsForwardDestination *> dests_;
    // The handler of the publishing stream, key is the stream url.
    std::map<std::string, ISrsForwardDestinationHandler *> handlers_;
    // To generate the id of destination.
    ISrsRand *rand_;

public:
    SrsForwardDestinations();
    virtual ~SrsForwardDestinations();

public:
    virtual srs_error_t add(SrsForwardDestination *dest, bool *created, SrsForwardDestination **pstored = NULL);
    virtual srs_error_t remove(std::string id);
    virtual SrsForwardDestination *find(std::string id);
    virtual void fetch(std::string stream_url, std::vector<SrsForwardDestination *> &dests);
    virtual void dumps(SrsForwardDestination *dest, SrsJsonObject *obj);

public:
    virtual void subscribe(std::string stream_url, ISrsForwardDestinationHandler *handler);
    virtual void unsubscribe(std::string stream_url, ISrsForwardDestinationHandler *handler);

// clang-format off
SRS_DECLARE_PRIVATE: // clang-format on
    virtual srs_error_t check(SrsForwardDestination *dest);
    virtual ISrsForwardDestinationHandler *handler_of(std::string stream_url);
};

// The global forward destinations, managed by the HTTP API.
extern ISrsForwardDestinations *_srs_forward_destinations;

#endif
