FROM ossrs/srs:ubuntu20-cache

ARG MAKEARGS
RUN echo "MAKEARGS: ${MAKEARGS}"

# https://serverfault.com/questions/949991/how-to-install-tzdata-on-a-ubuntu-docker-image
ENV DEBIAN_FRONTEND noninteractive

RUN apt update -y && apt install -y gcc make g++ patch unzip perl git libasan5 wget
# RUN apt install -y gcc make g++ patch unzip perl git libasan5

RUN wget https://go.dev/dl/go1.22.4.linux-amd64.tar.gz && \
    rm -rf /usr/local/go && tar -C /usr/local -xzf go1.22.4.linux-amd64.tar.gz && \
    rm go1.22.4.linux-amd64.tar.gz

# For go to build and run utest.
ENV PATH $PATH:/usr/local/go/bin

# Build and install SRS.
COPY . /srs
WORKDIR /srs/trunk

# Note that we must enable the gcc7 or link failed.
# Please note that we must disable the ffmpeg-opus, as it negatively impacts performance. We may consider
# enabling it in the future when support for multi-threading transcoding is available.
RUN ./configure --srt=on --gb28181=on --srt=on --apm=on --h265=on --utest=on --ffmpeg-opus=off --build-cache=off
RUN make utest ${MAKEARGS}

# Build benchmark tool.
RUN cd 3rdparty/srs-bench && make ${MAKEARGS}

