# Forward the stream to destinations which are added or removed by HTTP API at runtime.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;
http_api {
    enabled         on;
    listen          1985;
}
vhost __defaultVhost__ {
    forward {
        enabled     on;
        api         on;
    }
}
