#!/bin/bash
# Verify the `make install` recipe emitted by trunk/configure runs on this
# platform's sed, both GNU and BSD/macOS.
#
# Regression for the macOS failure:
#   sed: 1: "/Users/home/.local/etc/ ...": extra characters at the end of h command
# BSD sed requires an argument for -i, so `sed -i "s|...|...|g" FILE` consumes
# the script as the backup suffix and then parses FILE as the sed script.
set -e

usage() {
  cat <<'EOF'
Verify the install recipe generated by trunk/configure works with this sed.

Usage:
  install-target-test.sh        # run the test
  install-target-test.sh -h     # show this help
EOF
}

for arg in "$@"; do
  case "$arg" in
    -h|--help) usage; exit 0 ;;
    *)
      echo "Error: unknown argument: $arg" >&2
      usage >&2
      exit 2
      ;;
  esac
done

SCRIPT_DIR="$(cd -P "$(dirname "$0")" && pwd)"
# Walk up looking for trunk/configure, so the symlinked skills directory does
# not change the number of levels to the workspace root.
WORKSPACE="$SCRIPT_DIR"
while [[ "$WORKSPACE" != "/" && ! -f "$WORKSPACE/trunk/configure" ]]; do
  WORKSPACE="$(dirname "$WORKSPACE")"
done

if [[ ! -f "$WORKSPACE/trunk/configure" ]]; then
  echo "Error: trunk/configure not found walking up from: $SCRIPT_DIR" >&2
  exit 1
fi

cd "$WORKSPACE"

for cmd in sed grep awk find; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Error: required command not found: $cmd" >&2
    exit 1
  fi
done

WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/srs-install-test.XXXXXX")"
trap 'rm -rf "$WORK_DIR"' EXIT

FAILED=0
fail() {
  echo "FAIL: $1" >&2
  FAILED=1
}

# The install prefix reproduces the reported failure: BSD sed reads the path as
# a script, so /Users/... parses as the address /Users/ plus an `h` command.
PREFIX="$WORK_DIR/Users/home/.local"
DEFAULT_CONFIG="conf/srs.conf"

echo "Extracting the init.d step of the install recipe from trunk/configure"
# The recipe lives in a here-doc, so \$(VAR) becomes $(VAR) in the Makefile.
# The \" escapes survive into the Makefile and are unescaped by the shell that
# make runs the recipe with, so leave them alone here.
RECIPE="$WORK_DIR/recipe.sh"
awk '/^install:/{i=1} i && /Now copy init.d script files/{p=1; next} p && /Now copy systemctl/{exit} p' trunk/configure \
  | sed -e 's/^[[:space:]]*@//' -e 's/\\\$(/$(/g' \
  > "$RECIPE"

if ! grep -q 'sed ' "$RECIPE"; then
  echo "Error: no sed command found in the init.d step of trunk/configure" >&2
  exit 1
fi

sed -i.bak \
  -e "s|\$(__REAL_INSTALL)|$PREFIX|g" \
  -e "s|\$(SRS_PREFIX)|$PREFIX|g" \
  -e "s|\$(SRS_DEFAULT_CONFIG)|$DEFAULT_CONFIG|g" \
  "$RECIPE"
rm -f "$RECIPE.bak"

echo "Recipe under test:"
sed -e 's/^/  /' "$RECIPE"

echo "Running the recipe"
# make runs the recipe from trunk/, where its relative paths resolve.
if ! (cd trunk && bash -e "$RECIPE"); then
  fail "the install recipe exited non-zero with this platform's sed"
fi

echo "Checking the rewritten init.d script"
if ! grep -q "^ROOT=\"$PREFIX\"$" "$PREFIX/etc/init.d/srs"; then
  fail "ROOT= was not rewritten to the install prefix"
  grep -n '^ROOT=' "$PREFIX/etc/init.d/srs" >&2 || true
fi

if ! grep -q "^CONFIG=\"$DEFAULT_CONFIG\"$" "$PREFIX/etc/init.d/srs"; then
  fail "CONFIG= was not rewritten to the default config"
  grep -n '^CONFIG=' "$PREFIX/etc/init.d/srs" >&2 || true
fi

# BSD sed needs a backup suffix; the recipe must clean up whatever it creates
# so the install tree holds no stray editor backups.
LEFTOVERS="$(find "$PREFIX/etc/init.d" -type f ! -name 'srs' | sed -e 's/^/  /')"
if [[ -n "$LEFTOVERS" ]]; then
  fail "the install recipe left backup files behind:"
  echo "$LEFTOVERS" >&2
fi

if [[ $FAILED -ne 0 ]]; then
  echo "install-target-test: FAILED" >&2
  exit 1
fi

echo "install-target-test: PASSED"
